In [53]:
import pandas as pd

In [54]:
pd.DataFrame([1,2,3],columns=['A'],index=['A','B','c'])

   A
A  1
B  2
c  3

In [55]:
pd.DataFrame((1,2,3))

   0
0  1
1  2
2  3

In [56]:
pd.DataFrame({"Moths":["jan","Fed"],"Sales":[20,40]})

  Moths  Sales
0   jan     20
1   Fed     40

In [57]:
import numpy as np
np.random.seed(121)
df =pd.DataFrame(np.random.randint(0,10,(3,3)))

In [58]:
"A B C".split()

['A', 'B', 'C']

In [59]:
np.random.seed(121)
df = pd.DataFrame(np.random.randint(0,10(3,3)),columns="A B C".split(),index='P Q R'.split())
df

<>:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\Jaya krishna\AppData\Local\Temp\ipykernel_23708\2280823916.py:2: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  df = pd.DataFrame(np.random.randint(0,10(3,3)),columns="A B C".split(),index='P Q R'.split())

TypeError: 'int' object is not callable

In [60]:
df

   0  1  2
0  2  5  8
1  4  1  4
2  3  0  2

SyntaxError: invalid syntax (1048225456.py, line 1)

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\jaya krishna\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jaya krishna\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jaya krishna\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\jaya krishna\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 77.2 kB/s eta 0:02:02
   -- ------------------------------------- 0.5/9.9 MB 77.2 kB/s eta 0:02:02
   -- ------------------------------------- 0.5/9.9 MB 77.2 kB/s eta 0:02:02
   -- ------------------------------------- 0.5/9.9 MB 77.2 kB/s eta 0:02:02
   --- ------------------------------------ 0.8/9.9 MB 126.8 kB/s eta 0:01:12
   --- ------------------------------------ 0.8/9.9 MB 126.8 kB/s eta 0:01:12
   ---- ----------------------------------- 1.0/9.9 MB 168.7 kB/s eta 0:00:53
   ---- ----------------------------------- 1.0/9.9 MB 168.7 kB/s eta 0:00:53
   ---- ----------------------------------- 1.0/9.9 MB 168.7 kB/s eta 0:00:53
   ----- ---------------------------------- 1.3/9.9 MB 199.0 kB/s eta 0:00:44
   ----- ---------------------------------- 1.3/9.9 MB 199.0 kB/s eta 0:00:44
   ------ --------------------------------- 1.6/9.9 MB 230.1 kB/s eta 0:00:37
   ------ --------------------------------- 1.6/9.9 MB 230.1 kB/s eta 0:00:37
   ------ --------------------------------- 1.6/9.9 MB 230.1 kB/s eta 0:00:37
   ------- -------------------------------- 1.8/9.9 MB 251.6 kB/s eta 0:00:32
   ------- -------------------------------- 1.8/9.9 MB 251.6 kB/s eta 0:00:32
   -------- ------------------------------- 2.1/9.9 MB 270.2 kB/s eta 0:00:29
   -------- ------------------------------- 2.1/9.9 MB 270.2 kB/s eta 0:00:29
   -------- ------------------------------- 2.1/9.9 MB 270.2 kB/s eta 0:00:29
   -------- ------------------------------- 2.1/9.9 MB 270.2 kB/s eta 0:00:29
   --------- ------------------------------ 2.4/9.9 MB 280.8 kB/s eta 0:00:27
   --------- ------------------------------ 2.4/9.9 MB 280.8 kB/s eta 0:00:27
   --------- ------------------------------ 2.4/9.9 MB 280.8 kB/s eta 0:00:27
   ---------- ----------------------------- 2.6/9.9 MB 291.6 kB/s eta 0:00:25
   ---------- ----------------------------- 2.6/9.9 MB 291.6 kB/s eta 0:00:25
   ---------- ----------------------------- 2.6/9.9 MB 291.6 kB/s eta 0:00:25
   ---------- ----------------------------- 2.6/9.9 MB 291.6 kB/s eta 0:00:25
   ---------- ----------------------------- 2.6/9.9 MB 291.6 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.9 MB 282.9 kB/s eta 0:00:25
   ----------- ---------------------------- 2.9/9.9 MB 282.9 kB/s eta 0:00:25
   ------------ --------------------------- 3.1/9.9 MB 299.7 kB/s eta 0:00:23
   ------------ --------------------------- 3.1/9.9 MB 299.7 kB/s eta 0:00:23
   ------------- -------------------------- 3.4/9.9 MB 309.4 kB/s eta 0:00:21
   ------------- -------------------------- 3.4/9.9 MB 309.4 kB/s eta 0:00:21
   -------------- ------------------------- 3.7/9.9 MB 321.3 kB/s eta 0:00:20
   -------------- ------------------------- 3.7/9.9 MB 321.3 kB/s eta 0:00:20
   -------------- ------------------------- 3.7/9.9 MB 321.3 kB/s eta 0:00:20
   -------------- ------------------------- 3.7/9.9 MB 321.3 kB/s eta 0:00:20
   --------------- ------------------------ 3.9/9.9 MB 324.2 kB/s eta 0:00:19
   --------------- ------------------------ 3.9/9.9 MB 324.2 kB/s eta 0:00:19
   ---------------- ----------------------- 4.2/9.9 MB 335.0 kB/s eta 0:00:17
   ---------------- ----------------------- 4.2/9.9 MB 335.0 kB/s eta 0:00:17
   ---------------- ----------------------- 4.2/9.9 MB 335.0 kB/s eta 0:00:17
   ------------------ --------------------- 4.5/9.9 MB 339.7 kB/s eta 0:00:16
   ------------------- -------------------- 4.7/9.9 MB 352.2 kB/s eta 0:00:15
   ------------------- -------------------- 4.7/9.9 MB 352.2 kB/s eta 0:00:15
   ------------------- -------------------- 4.7/9.9 MB 352.2 kB/s eta 0:00:15
   ------------------- -------------------- 4.7/9.9 MB 352.2 kB/s eta 0:00:15
   -------------------- ------------------- 5.0/9.9 MB 350.8 kB/s eta 0:00:14
   -------------------- ------------------- 5.0/9.9 MB 350.8 kB/s eta 0:00:14
   --------------------- ------------------ 5.2/9.9 MB 360.4 kB/s eta 0:00:13
   --------------------- ------------------ 5.2/9.9 MB 360.4 kB/s eta 0:00:13
   --------------------- ------------------ 5.2/9.9 MB 360.4 kB/s eta 0:00:13
   ---------------------- ----------------- 5.5/9.9 MB 361.8 kB/s eta 0:00:13
   ---------------------- ----------------- 5.5/9.9 MB 361.8 kB/s eta 0:00:13
   ----------------------- ---------------- 5.8/9.9 MB 367.0 kB/s eta 0:00:12
   ----------------------- ---------------- 5.8/9.9 MB 367.0 kB/s eta 0:00:12
   ------------------------ --------------- 6.0/9.9 MB 372.9 kB/s eta 0:00:11
   ------------------------ --------------- 6.0/9.9 MB 372.9 kB/s eta 0:00:11
   ------------------------- -------------- 6.3/9.9 MB 379.6 kB/s eta 0:00:10
   ------------------------- -------------- 6.3/9.9 MB 379.6 kB/s eta 0:00:10
   -------------------------- ------------- 6.6/9.9 MB 388.7 kB/s eta 0:00:09
   -------------------------- ------------- 6.6/9.9 MB 388.7 kB/s eta 0:00:09
   --------------------------- ------------ 6.8/9.9 MB 392.0 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.9 MB 392.0 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.9 MB 392.0 kB/s eta 0:00:08
   --------------------------- ------------ 6.8/9.9 MB 392.0 kB/s eta 0:00:08
   ---------------------------- ----------- 7.1/9.9 MB 389.3 kB/s eta 0:00:08
   ---------------------------- ----------- 7.1/9.9 MB 389.3 kB/s eta 0:00:08
   ----------------------------- ---------- 7.3/9.9 MB 393.6 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.9 MB 393.6 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.9 MB 393.6 kB/s eta 0:00:07
   ----------------------------- ---------- 7.3/9.9 MB 393.6 kB/s eta 0:00:07
   ------------------------------ --------- 7.6/9.9 MB 389.0 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.9 MB 389.0 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.9 MB 389.0 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.9 MB 389.0 kB/s eta 0:00:06
   ------------------------------ --------- 7.6/9.9 MB 389.0 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.9 MB 383.5 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.9 MB 383.5 kB/s eta 0:00:06
   ------------------------------- -------- 7.9/9.9 MB 383.5 kB/s eta 0:00:06
   -------------------------------- ------- 8.1/9.9 MB 382.9 kB/s eta 0:00:05
   -------------------------------- ------- 8.1/9.9 MB 382.9 kB/s eta 0:00:05
   --------------------------------- ------ 8.4/9.9 MB 387.0 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 387.0 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 387.0 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 387.0 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 387.0 kB/s eta 0:00:04
   --------------------------------- ------ 8.4/9.9 MB 387.0 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.9 MB 376.8 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.9 MB 376.8 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.9 MB 376.8 kB/s eta 0:00:04
   ----------------------------------- ---- 8.7/9.9 MB 376.8 kB/s eta 0:00:04
   ------------------------------------ --- 8.9/9.9 MB 376.0 kB/s eta 0:00:03
   ------------------------------------- -- 9.2/9.9 MB 381.8 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 381.8 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 381.8 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.9 MB 381.8 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 380.9 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 380.9 kB/s eta 0:00:02
   -------------------------------------- - 9.4/9.9 MB 380.9 kB/s eta 0:00:02
   ---------------------------------------  9.7/9.9 MB 381.0 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 381.0 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 381.0 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 381.0 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 376.4 kB/s  0:00:27
Installing collected packages: pandas
Successfully installed pandas-3.0.3

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
import pandas as pd
df= pd.read_csv(r"C:\Users\Jaya krishna\OneDrive\New folder\pandas\Superstore sales dataset.csv")

In [15]:
df.shape

(9994, 21)

In [16]:
df.columns
df.head(2)
df.tail()
df.index

RangeIndex(start=0, stop=9994, step=1)

In [17]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [18]:
df[['Row ID','Order ID','Sales']].head(2)

   Row ID        Order ID   Sales
0       1  CA-2016-152156  261.96
1       2  CA-2016-152156  731.94

In [19]:
df.iloc[rows,columns]

NameError: name 'rows' is not defined

In [20]:
df.iloc[2:8,[2,5,7]]

   Order Date Customer ID    Segment
2  12-06-2016    DV-13045  Corporate
3  11-10-2015    SO-20335   Consumer
4  11-10-2015    SO-20335   Consumer
5  09-06-2014    BH-11710   Consumer
6  09-06-2014    BH-11710   Consumer
7  09-06-2014    BH-11710   Consumer

In [21]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [7]:
import numpy as np

In [8]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [9]:
np.finfo(np.float16).min

np.float16(-6.55e+04)

In [22]:
df.select_dtypes(include=['int64','float64']).head(2)

   Row ID  Postal Code   Sales  Quantity  Discount    Profit
0       1        42420  261.96         2       0.0   41.9136
1       2        42420  731.94         3       0.0  219.5820

In [23]:
df.select_dtypes(include=['str']).shape

(9994, 15)

In [24]:
df.shape

(9994, 21)

In [25]:
df.select_dtypes(include=['int64','float64']).shape

(9994, 6)

In [26]:
subset_df=df.iloc[0:5,0:5].copy()

In [27]:
subset_df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode'], dtype='str')

In [29]:
subset_df[['Row ID','Order ID','Ship Mode','Ship Date']].min()

Row ID                    1
Order ID     CA-2016-138688
Ship Mode      Second Class
Ship Date        11-11-2016
dtype: object

In [30]:
df[['Sales']].mean()

Sales    229.858001
dtype: float64

In [31]:
df['Ship Mode'].str.upper().head(2)

0    SECOND CLASS
1    SECOND CLASS
Name: Ship Mode, dtype: str

In [32]:
df['Ship Mode'].str.lower().head(2)

0    second class
1    second class
Name: Ship Mode, dtype: str

In [37]:
df['Ship Mode'].str.capitalize().head(2)

0    Second class
1    Second class
Name: Ship Mode, dtype: str

In [39]:
df['Ship Mode'].str.title().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [40]:
"data Science".capitalize()

'Data science'

In [41]:
df['Ship Mode'].str.len().head(2)

0    12
1    12
Name: Ship Mode, dtype: int64

In [42]:
df['Ship Mode'].str.strip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [45]:
" data ".strip()

'data'

In [46]:
df['Ship Mode'].str.lstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [47]:
df['Ship Mode'].str.rstrip().head(2)

0    Second Class
1    Second Class
Name: Ship Mode, dtype: str

In [48]:
df['Ship Mode'].str.split(" ").str[0]

0         Second
1         Second
2         Second
3       Standard
4       Standard
          ...
9989      Second
9990    Standard
9991    Standard
9992    Standard
9993      Second
Name: Ship Mode, Length: 9994, dtype: object

In [49]:
"91-733833".split("-")

['91', '733833']

In [50]:
"data science".split("a")

['d', 't', ' science']

In [51]:
df['Ship Mode'].str.count("Second")

0       1
1       1
2       1
3       0
4       0
       ..
9989    1
9990    0
9991    0
9992    0
9993    1
Name: Ship Mode, Length: 9994, dtype: int64

In [52]:
df["Ship Mode"].str.pad(width = 20,side='left',fillchar="-")

0       --------Second Class
1       --------Second Class
2       --------Second Class
3       ------Standard Class
4       ------Standard Class
                ...
9989    --------Second Class
9990    ------Standard Class
9991    ------Standard Class
9992    ------Standard Class
9993    --------Second Class
Name: Ship Mode, Length: 9994, dtype: str

In [1]:
## creating  preprocessing pipeline for the data

import pandas as pd

class preprocessingPipeline:
    def __int__(self,df):
        self.df = df


    # handling null values
    def null_value_treatment(self,tv):
        data = self.df
        ## calculating null values percenteages
        null_value_percentage = ((data.isna().sum())/data.shape[0])*100

        # droping colums whose null value threshold is  grater then
        columns_dropped = null_value_percentage[null_value_percentage >(tv * 100)].index
        columns_dropped = null_value_percentage[null_value_percentage< (tv *100)].index
        data = data.drop(columns =columns_dropped)
        print(data.shape,len(columns_dropped),len(columns_not_dropped))

        ## Return the final data
        return data
    ## optimising memory
    def memory_optimisation(self,df):
        pass

    ## handling outliers
    def outlier_treatment(self,df):
        pass

    ## enconding
    def categorial_encoding(self,df):
        pass

    ## Data splitting
    def Data_splitting(self,df):
        pass
    ## Exporatory data analysis
    def EDA(sekf,df):
        pass